POST http://localhost:3000/scores
Content-Type: application/json

{
  "questId": "4569bee2-8f42-4054-b432-68f6ddbc20b5", 
  "userId": "cb413e98-44a4-4bb1-aaa1-0b91ab1707e7", 
  "claimed_at": "2023-03-15T10:44:22+0000",
  "access_condition": [
    {
      "type": "discordRole", 
      "operator": "contains",
      "value": "1163897602547392553" 
    },
    {
      "type": "date",
      "value": "2023-02-15T10:44:22+0000",
      "operator": ">" 
    },
    {
      "type": "level",
      "value": "4",
      "operator": ">" 
    }
  ],
  "user_data": {
    "completed_quests": [
      "94e2e33e-07e9-4750-8cea-c033d7706057"
    ], 
    "discordRoles": ["1163897602547392553", "1194056197100286162"], 
    "level": 5
  },
  "submission_text": "Lorem ipsum dolor sit amet."
}

###

